EXP:
  ADVICE_METHOD: "ClipMLPNew"
  WANDB_SILENT: False
  PROJ: "LADS_CUB_Replication"
  SEED: 0
  TEXT_PROMPTS: [['a painting of a {} bird.'], ['art of a {} bird.'], ['a drawing of a {} bird.']]
  NEUTRAL_TEXT_PROMPTS: ['a photo of a {} bird.']
  AUGMENTATION: 'LADS'
  EPOCHS: 200
  ENSAMBLE: False
  LOG_NN: False

  
DATA:
  DATASET: "CUB"
  LOAD_CACHED: True
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    WEIGHT_DECAY: 0.05
    CHECKPOINT_NAME: 'lads'
    RESUME: False
  USE_DOM_GT: True

AUGMENTATION:
  MODEL:
    LR: 0.1
    WEIGHT_DECAY: 0.05
    NUM_LAYERS: 1
  GENERIC: False
  DOM_LABELS: ['painting', 'painting', 'painting']
  EPOCHS: 50