EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "LADS_GroZi"
  SEED: 0
  CHECKPOINT_NAME: "mlp"
  TEXT_PROMPTS: ['a stock photo of {}.']
  NEUTRAL_TEXT_PROMPTS: ['a blurry photo of {}.']
  EPOCHS: 200
  CHECKPOINT_VAL: True

DATA:
  DATASET: "GroZi"

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    CHECKPOINT: 'checkpoint/mlp.pth'
    CHECKPOINT_NAME: 'GroZi/mlp'
    RESUME: False

  USE_DOM_GT: False