EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "LADS_OfficeHomeProduct"
  SEED: 0
  TEXT_PROMPTS: ['art of a {}.', 'a photo of a {}.', 'clipart of a {}.']
  NEUTRAL_TEXT_PROMPTS: ['a stock photo of a {}.']
  EPOCHS: 400
  CHECKPOINT_VAL: True

DATA:
  DATASET: "OfficeHomeProduct"
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    LR: 0.005
    WEIGHT_DECAY: 0.05
    CHECKPOINT_NAME: 'cub_lp'