EXP:
  ADVICE_METHOD: "ClipMLPZS"
  WANDB_SILENT: False
  PROJ: "DomainNetMini_LADS_Replication"
  SEED: 0
  TEXT_PROMPTS: ['a painting of a {} bird.']
  NEUTRAL_TEXT_PROMPTS: ['a photo of a {} bird.']
  EPOCHS: 400
  CHECKPOINT_VAL: True
  TEMPLATES: 'domainnet_mini_templates'

DATA:
  DATASET: "DomainNetMini"
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    LR: 0.001
    WEIGHT_DECAY: 0.05
    CHECKPOINT_NAME: 'cub_lp'