EXP:
  ADVICE_METHOD: "ClipMLPZS"
  WANDB_SILENT: False
  PROJ: "LADS_OfficeHomeArt"
  SEED: 0
  TEXT_PROMPTS: ['art of a {}.', 'a stock photo of a {}.', 'a photo of a {}.']
  NEUTRAL_TEXT_PROMPTS: ['clipart of a {}.']
  EPOCHS: 200
  CHECKPOINT_VAL: True
  TEMPLATES: 'office_home_templates'

DATA:
  DATASET: "OfficeHomeArt"
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    LR: 0.005
    WEIGHT_DECAY: 0.05
    CHECKPOINT_NAME: 'officehome_product_lp'