EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "ColoredMNIST"
  SEED: 0
  AUGMENTATION: 'LADSBias'
  TEXT_PROMPTS: [['a photo of a red number {}.'], ['a photo of a blue number {}.']]
  NEUTRAL_TEXT_PROMPTS: ['a photo of a red number {}.', 'a photo of a blue number {}.']
  EPOCHS: 200
  CHECKPOINT_VAL: True
  ENSAMBLE: False

DATA:
  DATASET: "ColoredMNISTBinary"
  LOAD_CACHED: True
  BATCH_SIZE: 256
  ROOT: './data'

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    WEIGHT_DECAY: 0.05
    CHECKPOINT: 'checkpoint/mlp_simple.pth'
    CHECKPOINT_NAME: 'DomainNetMini/mlp-directional'
    RESUME: False
    HIDDEN_DIM: 512
  USE_DOM_GT: False

AUGMENTATION:
  MODEL:
    HIDDEN_DIM: 512
  ALPHA: 1
  EPOCHS: 50
  GENERIC: False
  DOM_SPECIFIC_XE: False
  CLIP_NN_LOSS: True
  NN_WEIGHT: 0.1
  DOM_WEIGHT: 10
  REG_WEIGHT: 0.1
  CYCLE_GAN_WEIGHT: 0