EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "LADS_OfficeHomeReal"
  SEED: 0
  TEXT_PROMPTS: ['art of a {}.', 'clipart of a {}.', 'a stock photo of a {}.']
  NEUTRAL_TEXT_PROMPTS: ['a real photo of a {}.']
  EPOCHS: 200
  CHECKPOINT_VAL: True

DATA:
  DATASET: "OfficeHomeClipart"
  BATCH_SIZE: 256

METHOD:
  MODEL:
    NUM_LAYERS: 1
    LR: 0.005
    WEIGHT_DECAY: 0.05
    CHECKPOINT_NAME: 'cub_lp'