EXP:
  ADVICE_METHOD: "ClipMLP"
  WANDB_SILENT: False
  PROJ: "LADS_Waterbirds_Rebuttal"
  SEED: 0
  TEXT_PROMPTS: [['a photo of a {} on forest.'], ['a photo of a {} on water.']]
  NEUTRAL_TEXT_PROMPTS: ['a photo of a {} on forest.', 'a photo of a {} on water.']
  AUGMENTATION: 'LADSBias'
  EPOCHS: 200
  CHECKPOINT_VAL: True
  ENSAMBLE: False
  
  
DATA:
  DATASET: "shapenet-modelnet"
  LOAD_CACHED: True
  BATCH_SIZE: 256
  ROOT: /shared/lisabdunlap/vl-attention/data

METHOD:
  MODEL:
    NUM_LAYERS: 1
    DOM_WEIGHT: 1.0
    LR: 0.001
    CHECKPOINT: 'checkpoint/mlp.pth'
    CHECKPOINT_NAME: "mlp"
    RESUME: False

AUGMENTATION:
  MODEL:
    LR: 0.005
    WEIGHT_DECAY: 0.005
    NUM_LAYERS: 1
    HIDDEN_DIM: 512
  EPOCHS: 50
  GENERIC: False
  DOM_LABELS: ["forest", "water"]
  DOM_SPECIFIC_XE: True
  ALPHA: 0.75
  COMPARE_BEFORE_AUG: True
  NN_INCLUDE_SAMPLE: True
