EXP:
  ADVICE_METHOD: "CLIPZS"
  WANDB_SILENT: False
  PROJ: "refactor"
  SEED: 0
  TEXT_PROMPTS: ['landbird', 'waterbird']
  # TEMPLATES: 'no_template'
  TEMPLATES: 'waterbirds_templates2'
  
DATA:
  DATASET: "Waterbirds"
  BATCH_SIZE: 256
  LOAD_CACHED: True
  UPWEIGHT_CLASSES: True
  ROOT: /shared/lisabdunlap/vl-attention/data